# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=60)),
                ('siteurl', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=60)),
                ('typeid', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='sitecollect',
            name='typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecollect.SiteType'),
        ),
    ]
