# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecollect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetype',
            name='typeid',
        ),
    ]
