# Generated by Django 2.0.4 on 2018-05-31 02:47

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='group name')),
                ('comment', models.CharField(blank=True, max_length=123, verbose_name='comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(default='', max_length=30, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(blank=True, default=users.models.date_expired_default, null=True, verbose_name='Date expired'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.UserGroup', verbose_name='user group'),
        ),
    ]
