# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostmanage', '0003_auto_20180323_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_zone', models.CharField(max_length=50)),
                ('gs_id', models.CharField(max_length=50)),
                ('gs_alias', models.CharField(max_length=50)),
                ('gs_accelerate_port', models.CharField(max_length=50)),
                ('gs_dir', models.CharField(max_length=50)),
                ('gs_name', models.CharField(max_length=50)),
                ('gs_db_name', models.CharField(max_length=50)),
                ('gs_db_log_name', models.CharField(max_length=50)),
                ('gs_db_outer_ip', models.CharField(max_length=50)),
                ('gs_db_inner_ip', models.CharField(max_length=50)),
                ('gs_status', models.CharField(max_length=50)),
                ('gs_open_time', models.CharField(max_length=50)),
                ('gs_branch', models.CharField(max_length=50)),
                ('gs_branch_commit_id', models.CharField(max_length=50)),
                ('gs_merged', models.CharField(max_length=50)),
                ('gs_merged_time', models.CharField(max_length=50)),
                ('gs_merged_to_id', models.CharField(max_length=50)),
                ('gs_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.Host')),
            ],
        ),
    ]
