# Generated by Django 2.0.4 on 2018-04-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conten', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='test', max_length=60, unique=True, verbose_name='链接名称')),
                ('siteurl', models.CharField(default='test', max_length=60, unique=True, verbose_name='链接地址')),
            ],
            options={
                'ordering': ['typeid'],
            },
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=60, unique=True, verbose_name='网址类型')),
            ],
        ),
        migrations.AddField(
            model_name='sitecollect',
            name='typeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecollect.SiteType', verbose_name='名称'),
        ),
    ]
