# Generated by Django 2.0.4 on 2018-04-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecollect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
