# Generated by Django 2.0 on 2018-04-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecollect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecollect',
            options={'ordering': ['typeid']},
        ),
        migrations.AlterModelOptions(
            name='sitetype',
            options={'ordering': ['id']},
        ),
    ]
