# Generated by Django 2.0.4 on 2018-04-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecollect', '0002_delete_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitetype',
            old_name='typename',
            new_name='site_type_name',
        ),
    ]
