# Generated by Django 2.0.4 on 2018-04-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecollect', '0003_auto_20180427_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteType',
            new_name='SiteTypeModel',
        ),
    ]
