# Generated by Django 2.0.4 on 2018-04-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecollect', '0004_auto_20180427_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteCollect',
            new_name='SiteCollectModel',
        ),
        migrations.AlterModelOptions(
            name='sitetypemodel',
            options={'ordering': ['id']},
        ),
    ]
