# Generated by Django 2.0.6 on 2018-07-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdb',
            name='host_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_info', to='hostmanage.Host', verbose_name="host name's id"),
        ),
    ]
