# Generated by Django 2.0.6 on 2018-08-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180719_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slavedb',
            name='db_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slave_info', to='db.MasterDb', verbose_name='从库'),
        ),
    ]
