# Generated by Django 2.0.6 on 2018-08-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180815_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='explain',
            field=models.CharField(blank=True, max_length=96, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='slavedb',
            name='explain',
            field=models.CharField(blank=True, max_length=96, verbose_name='说明'),
        ),
    ]
