# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50, null=True)),
                ('outer_ip', models.CharField(max_length=50)),
                ('inner_ip', models.CharField(max_length=50)),
                ('osversion', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=50, null=True)),
                ('disk', models.CharField(max_length=128, null=True)),
                ('cpu_num', models.CharField(max_length=50, null=True)),
                ('provider', models.CharField(max_length=50, null=True)),
                ('host_locate', models.CharField(max_length=50, null=True)),
                ('instance_id', models.CharField(max_length=50, null=True)),
                ('instance_name', models.CharField(max_length=50, null=True)),
                ('virtual_type', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('start_time', models.CharField(max_length=50, null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('project_name', models.CharField(max_length=50, null=True)),
                ('explain', models.CharField(max_length=128, null=True)),
            ],
            options={
                'ordering': ['outer_ip'],
            },
        ),
    ]
