# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPlat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=48)),
                ('cloud_platform_name', models.CharField(max_length=48)),
                ('locate', models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=48)),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_locate',
        ),
        migrations.RemoveField(
            model_name='host',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='provider',
        ),
        migrations.AddField(
            model_name='host',
            name='platfrom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.CloudPlat'),
        ),
        migrations.AddField(
            model_name='host',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.ProjectName'),
        ),
    ]
