# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0002_auto_20180412_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='platfrom_id',
            new_name='platfrom',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='project_id',
            new_name='project',
        ),
    ]
