# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0003_auto_20180412_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudplat',
            name='city',
            field=models.CharField(max_length=48, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='cloudplat',
            name='cloud_platform_name',
            field=models.CharField(max_length=48, verbose_name='云平台名字'),
        ),
        migrations.AlterField(
            model_name='cloudplat',
            name='locate',
            field=models.CharField(max_length=48, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='cloudplat',
            name='provider',
            field=models.CharField(max_length=48, verbose_name='提供商'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.CharField(max_length=50, null=True, verbose_name='cpu数量'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(max_length=128, null=True, verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='end_time',
            field=models.CharField(max_length=50, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='explain',
            field=models.CharField(max_length=128, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=50, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='inner_ip',
            field=models.CharField(max_length=50, verbose_name='内网ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='instance_id',
            field=models.CharField(max_length=50, null=True, verbose_name='实例id'),
        ),
        migrations.AlterField(
            model_name='host',
            name='instance_name',
            field=models.CharField(max_length=50, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(max_length=50, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='host',
            name='osversion',
            field=models.CharField(max_length=50, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='host',
            name='outer_ip',
            field=models.CharField(max_length=50, verbose_name='外网ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='platfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.CloudPlat', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.ProjectName', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='role',
            field=models.CharField(max_length=50, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='start_time',
            field=models.CharField(max_length=50, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='host',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='virtual_type',
            field=models.CharField(max_length=50, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='project_name',
            field=models.CharField(max_length=48, verbose_name='项目名'),
        ),
    ]
