# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0004_auto_20180412_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=48, verbose_name='角色')),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='role',
        ),
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.ManyToManyField(to='hostmanage.HostRole'),
        ),
    ]
