# Generated by Django 2.0.6 on 2018-07-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=48, verbose_name='type')),
                ('explain', models.CharField(blank=True, max_length=96, verbose_name='说明')),
            ],
        ),
        migrations.CreateModel(
            name='MasterDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=48, verbose_name='别名')),
                ('db_port', models.CharField(default=3306, max_length=42, verbose_name='database port')),
                ('status', models.CharField(max_length=42, verbose_name='database status, online of offline')),
                ('open_time', models.CharField(blank=True, max_length=42, verbose_name='database open time')),
                ('host_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_info', to='hostmanage.Host', verbose_name="host ip's id")),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_info', to='db.DbType', verbose_name='db type')),
            ],
            options={
                'ordering': ['id', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='SlaveDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=48, verbose_name='别名')),
                ('db_port', models.CharField(default=3306, max_length=42, verbose_name='database port')),
                ('status', models.CharField(max_length=42, verbose_name='database status, online of offline')),
                ('open_time', models.CharField(blank=True, max_length=42, verbose_name='database open time')),
                ('db_master', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.MasterDb', verbose_name='master info')),
                ('host_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slave_host_info', to='hostmanage.Host', verbose_name="host ip's id")),
            ],
            options={
                'ordering': ['id', 'alias'],
            },
        ),
    ]
