# Generated by Django 2.0.4 on 2018-06-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_slavedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=48, verbose_name='type')),
                ('explain', models.CharField(blank=True, max_length=96, verbose_name='说明')),
            ],
        ),
        migrations.AddField(
            model_name='masterdb',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_info', to='db.DbType', verbose_name='db type'),
        ),
    ]
