# Generated by Django 2.0.6 on 2018-07-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180627_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slavedb',
            name='db_master',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.MasterDb', verbose_name='master info'),
        ),
    ]
