# Generated by Django 2.0.4 on 2018-04-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPlat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=48, verbose_name='提供商')),
                ('cloud_platform_name', models.CharField(max_length=48, verbose_name='云平台名字')),
                ('locate', models.CharField(max_length=48, null=True, verbose_name='国家')),
                ('city', models.CharField(max_length=48, null=True, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('outer_ip', models.CharField(max_length=50, verbose_name='外网ip')),
                ('inner_ip', models.CharField(max_length=50, verbose_name='内网ip')),
                ('osversion', models.CharField(max_length=50, null=True, verbose_name='系统版本')),
                ('memory', models.CharField(max_length=50, null=True, verbose_name='内存')),
                ('disk', models.CharField(max_length=128, null=True, verbose_name='磁盘')),
                ('cpu_num', models.CharField(max_length=50, null=True, verbose_name='cpu数量')),
                ('instance_id', models.CharField(max_length=50, null=True, verbose_name='实例id')),
                ('instance_name', models.CharField(max_length=50, null=True, verbose_name='实例名字')),
                ('virtual_type', models.CharField(max_length=50, null=True, verbose_name='虚拟化类型')),
                ('start_time', models.CharField(max_length=50, null=True, verbose_name='注册时间 DateField')),
                ('end_time', models.CharField(max_length=50, null=True, verbose_name='销毁时间')),
                ('explain', models.CharField(max_length=128, null=True, verbose_name='说明')),
                ('platfrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.CloudPlat', verbose_name='区域')),
            ],
            options={
                'ordering': ['outer_ip'],
            },
        ),
        migrations.CreateModel(
            name='HostRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=48, unique=True, verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=48, unique=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=48, unique=True, verbose_name='项目名')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.ProjectName', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.ManyToManyField(to='hostmanage.HostRole', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostmanage.HostStatus', verbose_name='状态'),
        ),
    ]
