# Generated by Django 2.0.4 on 2018-05-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='roles', to='hostmanage.HostRole', verbose_name='角色'),
        ),
    ]
