# Generated by Django 2.0.4 on 2018-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cpu数量'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='销毁时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='explain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='inner_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='内网ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='instance_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实例id'),
        ),
        migrations.AlterField(
            model_name='host',
            name='instance_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实例名字'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='host',
            name='osversion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='host',
            name='outer_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='外网ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注册时间 DateField'),
        ),
        migrations.AlterField(
            model_name='host',
            name='virtual_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='虚拟化类型'),
        ),
    ]
