# Generated by Django 2.0.6 on 2018-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0002_auto_20180524_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudplat',
            name='zone',
            field=models.CharField(default='none', max_length=48, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='host',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
