# Generated by Django 2.0.6 on 2018-07-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0004_auto_20180713_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='hostmanage.ProjectName', verbose_name='项目'),
        ),
    ]
