# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FieTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(max_length=50)),
                ('outer_ip', models.CharField(max_length=50)),
                ('inner_ip', models.CharField(max_length=50)),
                ('osversion', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('cpu_num', models.CharField(max_length=50)),
                ('cloudplatform', models.CharField(max_length=50)),
                ('host_locate', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
