# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_locate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
