# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fie',
        ),
        migrations.DeleteModel(
            name='FieTest',
        ),
    ]
