# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0003_auto_20180323_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='end_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='instance_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='instance_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='project_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='start_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='virtual_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
