# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0004_auto_20180326_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cloudplatform',
        ),
        migrations.AddField(
            model_name='host',
            name='explain',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='osversion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
