# Generated by Django 2.0.6 on 2018-07-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostmanage', '0005_auto_20180716_1033'),
        ('db', '0004_auto_20180702_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='GsConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('used', models.CharField(max_length=50, verbose_name='是否使用')),
                ('gs_id', models.IntegerField(verbose_name='游戏服id')),
                ('gs_alias', models.CharField(max_length=50, verbose_name='唯一标识符')),
                ('gs_accelerate_port', models.CharField(max_length=50, verbose_name='加速端口')),
                ('gs_dir', models.CharField(max_length=50, verbose_name='游戏服目录')),
                ('gs_name', models.CharField(max_length=50, verbose_name='游戏服名字')),
                ('gs_open_time', models.DateTimeField(null=True, verbose_name='开服时间')),
                ('gs_branch', models.CharField(max_length=50, verbose_name='分支名')),
                ('gs_branch_commit_id', models.CharField(max_length=50, verbose_name='分支的commit id')),
                ('gs_merged', models.CharField(max_length=50, verbose_name='是否合服')),
                ('gs_merged_time', models.CharField(max_length=50, verbose_name='合服时间')),
                ('gs_merged_to_id', models.CharField(max_length=50, verbose_name='合入id')),
                ('gs_db_name', models.CharField(blank=True, max_length=42, null=True, verbose_name='database name')),
                ('gs_log_db_name', models.CharField(blank=True, max_length=42, null=True, verbose_name='database log name')),
                ('dau', models.IntegerField(null=True, verbose_name='')),
                ('power_alliance_m', models.FloatField(null=True, verbose_name='')),
                ('power_m', models.FloatField(null=True, verbose_name='实力')),
                ('udid', models.IntegerField(null=True, verbose_name='')),
                ('users', models.IntegerField(null=True, verbose_name='用户数量')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('gs_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_db', to='db.MasterDb', verbose_name='main db')),
                ('gs_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_ip_info', to='hostmanage.Host', verbose_name="host ip's id")),
            ],
            options={
                'ordering': ['gs_zone', 'gs_id'],
            },
        ),
        migrations.CreateModel(
            name='GsStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=48, unique=True, verbose_name='字段id')),
                ('status_explain', models.CharField(blank=True, max_length=48, verbose_name='字段说明')),
            ],
            options={
                'ordering': ['id', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=48, unique=True, verbose_name='标签')),
                ('tag_explain', models.CharField(blank=True, max_length=128, null=True, verbose_name='标签说明')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ZoneName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=48, verbose_name='区域')),
                ('zone_name_explain', models.CharField(blank=True, max_length=48, verbose_name='zone说明')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='gsconfig',
            name='gs_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_status', to='cmdb.GsStatus', verbose_name='gs status id'),
        ),
        migrations.AddField(
            model_name='gsconfig',
            name='gs_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_zone_name', to='cmdb.ZoneName', verbose_name='zone id，安卓 or ios'),
        ),
        migrations.AddField(
            model_name='gsconfig',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='gs_tag', to='cmdb.Tag', verbose_name='标签字段'),
        ),
    ]
