# Generated by Django 2.0 on 2018-04-26 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmanage',
            name='gs_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_zone_name_set', to='cmdb.ZoneName', verbose_name='zone id'),
        ),
    ]
