# Generated by Django 2.0.4 on 2018-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmanage',
            name='project',
        ),
        migrations.AlterField(
            model_name='configmanage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
