# Generated by Django 2.0.4 on 2018-05-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsstatus',
            name='status_explain',
            field=models.CharField(blank=True, max_length=48, verbose_name='字段说明'),
        ),
        migrations.AlterField(
            model_name='gsstatus',
            name='status',
            field=models.CharField(max_length=48, unique=True, verbose_name='字段id'),
        ),
    ]
