# Generated by Django 2.0.4 on 2018-06-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180523_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmanage',
            name='gs_db',
        ),
        migrations.RemoveField(
            model_name='configmanage',
            name='gs_log_db',
        ),
        migrations.AddField(
            model_name='dbconfig',
            name='config_manage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.ConfigManage', verbose_name='db_config'),
        ),
    ]
