# Generated by Django 2.0 on 2018-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180426_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonename',
            name='contry',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_name',
            field=models.CharField(max_length=48),
        ),
    ]
