# Generated by Django 2.0.4 on 2018-05-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180521_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconfig',
            options={'ordering': ['host_ip', 'db_name']},
        ),
    ]
