# Generated by Django 2.0 on 2018-04-26 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180426_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmanage',
            name='gs_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_db_set', to='cmdb.DbConfig', verbose_name='gs db id'),
        ),
        migrations.AddField(
            model_name='configmanage',
            name='gs_log_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_log_db_set', to='cmdb.DbConfig', verbose_name='gs log db id'),
        ),
    ]
