# Generated by Django 2.0.4 on 2018-06-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_remove_dbconfig_db_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsstatus',
            options={'ordering': ['id', 'status']},
        ),
        migrations.AddField(
            model_name='dbconfig',
            name='db_type',
            field=models.CharField(max_length=48, null=True, verbose_name='数据库用途'),
        ),
    ]
