# Generated by Django 2.0.4 on 2018-06-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180606_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonename',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='configmanage',
            name='gs_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_ip_info', to='hostmanage.Host', verbose_name="host ip's id"),
        ),
        migrations.AlterField(
            model_name='configmanage',
            name='gs_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_status', to='cmdb.GsStatus', verbose_name='gs status id'),
        ),
        migrations.AlterField(
            model_name='configmanage',
            name='gs_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_zone_name', to='cmdb.ZoneName', verbose_name='zone id'),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='config_manage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_manage', to='cmdb.ConfigManage', verbose_name='db_config'),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='host_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_ip', to='hostmanage.Host', verbose_name="host ip's id"),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='contry',
            field=models.CharField(max_length=48, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_name',
            field=models.CharField(max_length=48, verbose_name='区域'),
        ),
    ]
