# Generated by Django 2.0.4 on 2018-06-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0002_auto_20180524_1115'),
        ('cmdb', '0006_auto_20180615_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigManage',
            new_name='GsConfig',
        ),
    ]
