# Generated by Django 2.0.4 on 2018-06-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20180615_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=48, unique=True, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='gsconfig',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_tag', to='cmdb.Tag', verbose_name='标签字段'),
        ),
    ]
