# Generated by Django 2.0.4 on 2018-06-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0002_auto_20180524_1115'),
        ('cmdb', '0008_auto_20180620_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsconfig',
            name='gs_db_name',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='database name'),
        ),
        migrations.AddField(
            model_name='gsconfig',
            name='gs_log_db_name',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='database log name'),
        ),
        migrations.AddField(
            model_name='gsconfig',
            name='gs_slave_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_slave_ip', to='hostmanage.Host', verbose_name="slave db ip's id"),
        ),
        migrations.AlterField(
            model_name='gsconfig',
            name='gs_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_ip', to='hostmanage.Host', verbose_name="db ip's id"),
        ),
    ]
