# Generated by Django 2.0.4 on 2018-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20180620_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonename',
            name='contry',
        ),
        migrations.AddField(
            model_name='zonename',
            name='zone_name_explain',
            field=models.CharField(blank=True, max_length=48, verbose_name='zone说明'),
        ),
    ]
