# Generated by Django 2.0.4 on 2018-06-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20180620_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsconfig',
            name='gs_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_zone_name', to='cmdb.ZoneName', verbose_name='zone id，安卓 or ios'),
        ),
    ]
