# Generated by Django 2.0.4 on 2018-06-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0002_auto_20180524_1115'),
        ('cmdb', '0013_auto_20180620_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbconfig',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='dbconfig',
            name='config_manage',
        ),
        migrations.RemoveField(
            model_name='dbconfig',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='dbconfig',
            name='db_type',
        ),
        migrations.RemoveField(
            model_name='dbconfig',
            name='host_ip',
        ),
        migrations.AddField(
            model_name='dbconfig',
            name='master_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_ip_info', to='hostmanage.Host', verbose_name="master ip's id"),
        ),
        migrations.AddField(
            model_name='dbconfig',
            name='slave_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slave_ip_info', to='hostmanage.Host', verbose_name="slave ip's id"),
        ),
    ]
