# Generated by Django 2.0.4 on 2018-06-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20180620_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsconfig',
            name='gs_db_slave_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_db_slave_ip_info', to='cmdb.DbConfig', verbose_name="db ip's id"),
        ),
    ]
