# Generated by Django 2.0.4 on 2018-06-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0019_auto_20180625_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsconfig',
            name='gs_db_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_db_info', to='cmdb.DbConfig', verbose_name='数据库信息'),
        ),
    ]
