# Generated by Django 2.0.6 on 2018-07-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180702_1005'),
        ('cmdb', '0020_gsconfig_gs_db_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsconfig',
            name='gs_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gs_db', to='db.MasterDb', verbose_name='main db'),
        ),
    ]
