# Generated by Django 2.0.6 on 2018-07-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_auto_20180716_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsconfig',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='gsconfig',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
