# Generated by Django 2.0.6 on 2018-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststatus',
            name='explain',
            field=models.CharField(max_length=128, null=True, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='explain',
            field=models.CharField(max_length=128, null=True, verbose_name='说明'),
        ),
    ]
